### ISSUE TITLE
如何不使用CUDA运行

### ISSUE THREAD

**Issue by GaoZhipengCN** [Tele-AI/TeleSpeech-ASR#31]
./decode.sh
INFO:__main__:import user_dir: /Users/gao/TeleSpeech-ASR/data2vec_dialect
Traceback (most recent call last):
  File "/Users/gao/TeleSpeech-ASR/data2vec_dialect/run_scripts/../infer.py", line 464, in hydra_main
    distributed_utils.call_main(cfg, main)
  File "/Users/gao/fairseq/fairseq/distributed/utils.py", line 404, in call_main
    main(cfg, **kwargs)
  File "/Users/gao/TeleSpeech-ASR/data2vec_dialect/run_scripts/../infer.py", line 408, in main
    raise ValueError("CUDA not found; set `cpu=True` to run without CUDA")
ValueError: CUDA not found; set `cpu=True` to run without CUDA

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by TTTdas** [comment]
在执行decode.sh脚本中，添加一行common.cpu=true \

**Comment by GaoZhipengCN** [comment]
谢谢，已解决。
通过在infer.py中的def main(cfg: InferConfig) -> float:开头添加cfg.common.cpu = True
